name: Deploy static site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}

jobs:
  terraform:
    name: Terraform plan/apply
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # OIDC for AWS
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform fmt
        working-directory: terraform
        run: terraform fmt

      - name: Terraform validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform plan (PR)
        if: github.event_name == 'pull_request'
        working-directory: terraform
        run: terraform plan -var-file="env/prod.tfvars" -input=false -no-color

      - name: Terraform apply (main)
        if: github.event_name == 'push'
        working-directory: terraform
        env:
          # TF needs to know the name of the bucket when using var.s3_bucket_name
          TF_VAR_s3_bucket_name: ${{ env.S3_BUCKET }}
        run: terraform apply -var-file="env/prod.tfvars" -auto-approve -input=false

  sync_static:
    name: Sync static files to S3
    runs-on: ubuntu-latest
    needs: terraform   # wait for successful Terraform
    if: github.event_name == 'push' # only when push (merge to main)

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync src/ to S3
        run: |
          aws s3 sync src/ s3://${S3_BUCKET} \
            --delete \
            --cache-control "max-age=300"